language: node_js

node_js:
  - "8"

install:
  - npm install

script:
  - npm run build:check

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
